version: '2'
services:
  master:
    image: pavics/jenkins-master:2.190.3.191129
    hostname: jenkins_master
    ports:
      - "${JENKINS_MASTER_PORT}:8080"
    volumes:
      - master_home:/var/jenkins_home
      - ./buildout/jcasc_config:/jcasc:ro
    environment:
      - CASC_JENKINS_CONFIG=/jcasc/
      - SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY}
      - ADMIN_PASSWD=$JENKINS_ADMIN_PASSWD
      - HTTP_PROTO=$JENKINS_HTTP_PROTO
      - HOSTNAME=$JENKINS_HOSTNAME
      - HOSTPORT=$JENKINS_MASTER_PORT
      - NUM_EXECUTORS=$JENKINS_NUM_EXECUTORS_LOCAL
      - ESGF_AUTH_USERNAME=$JENKINS_ESGF_AUTH_USERNAME
      - ESGF_AUTH_PASSWORD=$JENKINS_ESGF_AUTH_PASSWORD
      - ESGF_AUTH_TOKEN=$JENKINS_ESGF_AUTH_TOKEN
      - IS_PROD=$JENKINS_IS_PROD
      - ENABLE_SCHEDULED_TRIGGER=$JENKINS_ENABLE_SCHEDULED_TRIGGER
      - DEFAULT_PAVICS_HOST=$JENKINS_DEFAULT_PAVICS_HOST
    links:
      - slave
    restart: always

  slave:
    image: pavics/jenkins-ssh-slave:190226
    hostname: jenkins_slave
    volumes:
      - slave_home:/home/jenkins
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_SLAVE_SSH_PUBKEY=$JENKINS_SLAVE_SSH_PUBKEY
      - DOCKER_GROUP_ON_HOST=$DOCKER_GROUP_ON_HOST
    restart: always

volumes:
  master_home:
    external:
      name: jenkins_master_home_$JENKINS_MASTER_PORT
  slave_home:
    external:
      name: jenkins_slave_home_$JENKINS_MASTER_PORT

# vi: tabstop=8 expandtab shiftwidth=2 softtabstop=2
