jobs:
  - script: >
      folder('ouranos-staging')
  - script: >
      pipelineJob('ouranos-staging/medus.ouranos.ca') {
        description('Run nightlies on staging server medus.ouranos.ca.')
        definition {
          cpsScm {
            scriptPath 'Jenkinsfile'
            scm {
              git {
                remote {
                  url('https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests.git')
                }
                branch('master')
                extensions {
                  cleanAfterCheckout()
                }
              }
            }
            lightweight true
          }
        }

        environmentVariables {
          env('DEFAULT_PAVICS_HOST', 'medus.ouranos.ca')

          // Needed for first build, else will use default that is not this default.
          env('PAVICS_HOST', 'medus.ouranos.ca')
        }

        triggers {
          // Same cron as in Jenkinsfile but need to "seed" it here for first build to run.
          // Settings in Jenkinsfiles will only apply after first build.
          cron('@midnight')
        }
      }


# vi: tabstop=8 expandtab shiftwidth=2 softtabstop=2
