jobs:
  - script: >
      folder('variant-builds')

  - script: >
      pipelineJob('variant-builds/read-only-checkout') {
        description('Run the builds with the entire checkout read-only.')
        definition {
          cpsScm {
            scriptPath 'Jenkinsfile'
            scm {
              git {
                remote {
                  url('https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests.git')
                }
                branch('master')
                extensions {
                  cleanAfterCheckout()
                }
              }
            }
            lightweight true
          }
        }

        environmentVariables {
          // This section requires the envinject plugin.
          // It is known that envinject do not work properly with pipeline.
          // "These EnvVars are being injected to the script environment and
          // will be inaccessible via the "env" Pipeline global variable"

          // Can not use DEFAULT_CONFIG_PARAMETERS_SCRIPT_URL because it seems
          // we can not override global env var.
          env('CI_OVERRIDE_CONFIG_PARAMETERS_SCRIPT_URL', 'https://raw.githubusercontent.com/Ouranosinc/PAVICS-e2e-workflow-tests/refs/heads/master/test-override/jenkins-params-readonly-checkout.include.sh')
        }

        triggers {
          // Same cron as in Jenkinsfile but need to "seed" it here for first build to run.
          // Settings in Jenkinsfiles will only apply after first build.
          //cron('@midnight')
        }
      }


# vi: tabstop=8 expandtab shiftwidth=2 softtabstop=2
